base_url = "https://jamesbradbury.net"
compile_sass = true
build_search_index = false
generate_feeds = true

[markdown]
highlight_code = true

[extra]
release_code = ""
full_name = "James Bradbury "
given_name = "James"
family_name = "Bradbury"
profile_image = "/front.jpg"
job_title = "Software Developer"
email = "hi@jamesbradbury.net"
social_profiles = [
    "https://twitter.com/james_bradbury_",
    "https://github.com/jamesb93"
]
description = "Creative-coder and experimental electronic artist from Perth, Western Australia. Machine listening, learning, Max, REAPER, Python are my bread and butter."
