base_url = "https://jamesbradbury.net"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
release_code = ""
full_name = "James Bradbury "
given_name = "James"
family_name = "Bradbury"
profile_image = "/front.jpg"
job_title = "Software Developer"
email = "hi@jamesbradbury.net"
social_profiles = [
    "https://twitter.com/james_bradbury_",
    "https://github.com/jamesb93"
]
description = "I am a creative-coder and artist from Perth, Western Australia currently living in Berlin. I enjoy programming in my practice often harnessing the computer to find and organise audio-samples through machine listening and learning. I used to work as a Research Fellow in Creative Coding on the Fluid Corpus Manipulation project. I now work at Ableton on Research and Development. I'm currently working on projects with Mark Fell and Rian Treanor at https://intersymmetric.xyz, as well as creating devices with MONOMONO."
